from django.db import models
from heroes.models import Hero

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length = 50)
    json_response = models.CharField(max_length = 10000)
    riot_id = models.IntegerField()
    tag = models.CharField(max_length = 100)
    image = models.CharField(max_length = 1000)
    FlatArmorMod = models.IntegerField(default = 0, blank = True, null = True)  
    FlatAttackSpeedMod = models.IntegerField(default = 0, blank = True, null = True)   
    FlatBlockMod = models.IntegerField(default = 0, blank = True, null = True)     
    FlatCritChanceMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatCritDamageMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatEXPBonus = models.IntegerField(default = 0, blank = True, null = True)     
    FlatEnergyPoolMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatEnergyRegenMod = models.IntegerField(default = 0, blank = True, null = True)   
    FlatHPPoolMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatHPRegenMod = models.IntegerField(default = 0, blank = True, null = True)   
    FlatMPPoolMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatMPRegenMod = models.IntegerField(default = 0, blank = True, null = True)   
    FlatMagicDamageMod = models.IntegerField(default = 0, blank = True, null = True)   
    FlatMovementSpeedMod = models.IntegerField(default = 0, blank = True, null = True)     
    FlatPhysicalDamageMod = models.IntegerField(default = 0, blank = True, null = True)    
    FlatSpellBlockMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentArmorMod = models.IntegerField(default = 0, blank = True, null = True)  
    PercentAttackSpeedMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentBlockMod = models.IntegerField(default = 0, blank = True, null = True)  
    PercentCritChanceMod = models.IntegerField(default = 0, blank = True, null = True)     
    PercentCritDamageMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentDodgeMod = models.IntegerField(default = 0, blank = True, null = True)
    PercentEXPBonus = models.IntegerField(default = 0, blank = True, null = True)  
    PercentHPPoolMod = models.IntegerField(default = 0, blank = True, null = True)     
    PercentHPRegenMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentLifeStealMod = models.IntegerField(default = 0, blank = True, null = True)  
    PercentMPPoolMod = models.IntegerField(default = 0, blank = True, null = True)     
    PercentMPRegenMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentMagicDamageMod = models.IntegerField(default = 0, blank = True, null = True)    
    PercentMovementSpeedMod = models.IntegerField(default = 0, blank = True, null = True)  
    PercentPhysicalDamageMod = models.IntegerField(default = 0, blank = True, null = True)     
    PercentSpellBlockMod = models.IntegerField(default = 0, blank = True, null = True)     
    PercentSpellVampMod = models.IntegerField(default = 0, blank = True, null = True)
    rFlatArmorModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatArmorPenetrationMod = models.IntegerField(default = 0, blank = True, null = True)     
    rFlatArmorPenetrationModPerLevel = models.IntegerField(default = 0, blank = True, null = True)     
    rFlatCritChanceModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatCritDamageModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatDodgeMod = models.IntegerField(default = 0, blank = True, null = True)    
    rFlatDodgeModPerLevel = models.IntegerField(default = 0, blank = True, null = True)    
    rFlatEnergyModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatEnergyRegenModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rFlatGoldPer10Mod = models.IntegerField(default = 0, blank = True, null = True)    
    rFlatHPModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatHPRegenModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rFlatMPModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatMPRegenModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rFlatMagicDamageModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rFlatMagicPenetrationMod = models.IntegerField(default = 0, blank = True, null = True)    
    rFlatMagicPenetrationModPerLevel = models.IntegerField(default = 0, blank = True, null = True)     
    rFlatMovementSpeedModPerLevel = models.IntegerField(default = 0, blank = True, null = True)    
    rFlatPhysicalDamageModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatSpellBlockModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rFlatTimeDeadMod = models.IntegerField(default = 0, blank = True, null = True)     
    rFlatTimeDeadModPerLevel = models.IntegerField(default = 0, blank = True, null = True)      
    rPercentArmorPenetrationMod = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentArmorPenetrationModPerLevel = models.IntegerField(default = 0, blank = True, null = True)   
    rPercentAttackSpeedModPerLevel = models.IntegerField(default = 0, blank = True, null = True)    
    rPercentCooldownMod = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentCooldownModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentMagicPenetrationMod = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentMagicPenetrationModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentMovementSpeedModPerLevel = models.IntegerField(default = 0, blank = True, null = True)      
    rPercentTimeDeadMod = models.IntegerField(default = 0, blank = True, null = True)  
    rPercentTimeDeadModPerLevel = models.IntegerField(default = 0, blank = True, null = True)  

    def __unicode__(self):
        return unicode("Riot ID "+str(self.riot_id)+" "+self.name)

class ItemTag(models.Model):
	item = models.ForeignKey(Item)
	tag = models.CharField(max_length = 20)
